# Generated by Django 5.1.2 on 2024-10-25 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='collection_name',
        ),
    ]
