# Generated by Django 5.1.2 on 2024-10-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_remove_bookmark_collection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='priority',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='note',
            field=models.TextField(default="There's no note yet"),
        ),
    ]
