# Generated by Django 5.1.1 on 2024-10-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_driven', models.IntegerField()),
                ('image_url', models.URLField()),
                ('dealer', models.CharField(max_length=255)),
            ],
        ),
    ]
