# Generated by Django 5.1.1 on 2024-10-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_privelege',
            field=models.CharField(default='customer', max_length=10),
        ),
    ]
