# Generated by Django 5.1.2 on 2024-10-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_cart'),
        ('authentication', '0003_rename_full_name_userprofile_name'),
    ]

    operations = [
    ]
