# Generated by Django 5.1.1 on 2024-10-24 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_full_name_userprofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_privelege',
            new_name='privilege',
        ),
    ]
