# Generated by Django 5.1.1 on 2024-10-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_merge_20241024_1206'),
        ('authentication', '0004_rename_user_privelege_userprofile_privilege'),
    ]

    operations = [
    ]
