# Generated by Django 5.1.1 on 2024-10-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_user_privelege_userprofile_user_privilege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_privilege',
            new_name='privilege',
        ),
    ]
