# Generated by Django 5.1.2 on 2024-10-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_20241026_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cart',
        ),
    ]
